name: Mihai Dobri
url: http://www.mihaidobri.com
description: Mihai Dobri's homepage
permalink: /blog/:title
markdown: kramdown
highlighter: true
lsi: true
include: [".well-known"]
exclude: [
  Gemfile, Gemfile.lock, nginx.conf, CNAME, nginx.common.conf, README.md,
  post-receive.sh
]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

sass:
  style: :compressed

theme: jekyll-theme-minimal