site_name: George's Awesome Website
site_url: https://github.com/gmihaila/gmihaila.github.io
repo_name: 'Machine Learning Things'
repo_url: https://github.com/gmihaila/machine_learning_things
edit_uri: tree/master/docs/src/markdown
site_description: George's Website along with a Collection of Useful Snippets for Python Machine Learning
copyright: |
  Copyright &copy; 2015 - 2020 <a href="https://github.com/gmihaila"  target="_blank" rel="noopener">George Mihaila</a>

docs_dir: markdown

nav:
    - About: index.md
    
    - Activities: activities/activities.md
    
    - Useful Code: useful/useful.md
        
    - Resume: resume/resume.md


markdown_extensions:
    - markdown.extensions.toc:
        slugify: !!python/name:pymdownx.slugs.uslugify
        permalink: ""
    - markdown.extensions.admonition:
    - markdown.extensions.smarty:
        smart_quotes: false
    - pymdownx.betterem:
    - markdown.extensions.attr_list:
    - markdown.extensions.def_list:
    - markdown.extensions.tables:
    - markdown.extensions.abbr:
    - markdown.extensions.footnotes:
    - markdown.extensions.md_in_html:
    - pymdownx.superfences:
        preserve_tabs: true
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
    - pymdownx.highlight:
        extend_pygments_lang:
          - name: php-inline
            lang: php
            options:
              startinline: true
          - name: pycon3
            lang: pycon
            options:
              python3: true
        linenums_style: pymdownx-inline
    - pymdownx.inlinehilite:
        custom_inline:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
    - pymdownx.magiclink:
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shorthand: true
        social_url_shortener: true
        user: facelessuser
        repo: pymdown-extensions
    - pymdownx.tilde:
    - pymdownx.caret:
    - pymdownx.smartsymbols:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.escapeall:
        hardbreak: True
        nbsp: True
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.progressbar:
    - pymdownx.arithmatex:
    - pymdownx.mark:
    - pymdownx.striphtml:
    - pymdownx.snippets:
        base_path: markdown/_snippets
    - pymdownx.keys:
        separator: "\uff0b"
    - pymdownx.details:
    - pymdownx.tabbed:

    
theme:
    name: material
    custom_dir: theme
    icon:
        logo: material/book-open-page-variant
    language: en
    features:
        - instant
    palette:
        primary: black
        accent: black
    font:
        text: Roboto
        code: Roboto Mono
        
extra:
    manifest: manifest.webmanifest
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/gmihaila
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mihailageorge

    
extra_css:
    - assets/pymdownx-extras/extra.css

extra_javascript:
    - assets/pymdownx-extras/extra.js
    
plugins:
    - search
